apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-agent-fi
  labels:
    app: ado-agent-fi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ado-agent-fi
  template:
    metadata:
      name: ado-agent-fi
      labels:
        app: ado-agent-fi
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ado-agent-sa
      containers:
        - name: ado-agent-fi
          image: acraksregistry.azurecr.io/ado-agent:latest  # ✅ Use your pushed image here
          imagePullPolicy: Always
          env:
            - name: AZP_URL
              value: https://dev.azure.com/nkdyo454
            - name: AZP_POOL
              value: agent-mi
            - name: AZP_AGENT_NAME
              value: agent-mi-auto
            - name: AZURE_CLIENT_ID
              value: 72680213-f085-427d-9c8c-a01b5387f8ad  # 👈 From your managed identity
            - name: AZURE_TENANT_ID
              value: 871621f4-3a19-401e-a9f8-4e1241121767
          volumeMounts:
            - name: federated-token
              mountPath: /var/run/secrets/azure/tokens
              readOnly: true
      volumes:
        - name: federated-token
          projected:
            sources:
              - serviceAccountToken:
                  path: federated-token
                  expirationSeconds: 3600
                  audience: api://AzureADTokenExchange
      restartPolicy: Always
