airflow:
  # Airflow executor type (use KubernetesExecutor for Kubernetes)
  executor: KubernetesExecutor

  # Set the Airflow image tag (e.g., the Airflow version to use)
  image:
    repository: apache/airflow
    tag: "2.5.1"  # Update to the desired version of Airflow

  # Database settings
  database:
    user: airflow
    password: airflow
    host: airflow-db
    port: 5432
    db: airflow

  # Optional: Configure the airflow home directory
  airflowHome: /opt/airflow

  # Enable RBAC for Airflow UI
  rbac:
    create: true

webserver:
  # Webserver configuration (SSO settings)
  extraEnv:
    - name: AIRFLOW__WEBSERVER__WEB_SERVER_CONFIG_PATH
      value: /opt/airflow/webserver_config.py

  # Mount the configmap containing the webserver_config.py
  volumes:
    - name: airflow-webserver-config
      configMap:
        name: airflow-webserver-config
  volumeMounts:
    - name: airflow-webserver-config
      mountPath: /opt/airflow/webserver_config.py
      subPath: webserver_config.py

  configMountPath: /opt/airflow/webserver_config.py
  replicas: 2

  service:
    # Configure the service type for the web server
    type: LoadBalancer

scheduler:
  replicas: 2  # Number of scheduler replicas

workers:
  replicas: 3  # Number of worker pods

resources:
  webserver:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  scheduler:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  workers:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
