airflow:
  # Airflow executor type (use KubernetesExecutor for Kubernetes)
  executor: KubernetesExecutor

  # Set the Airflow image tag (e.g., the Airflow version to use)
  image:
    repository: apache/airflow
    tag: "2.5.1"  # Update to the desired version of Airflow

  # Database settings
  database:
    user: airflow
    password: airflow
    host: airflow-db
    port: 5432
    db: airflow

  # Optional: Configure the airflow home directory
  airflowHome: /opt/airflow

  # Enable RBAC for Airflow UI
  rbac:
    create: true
   
webserver:
  webserverConfig: |
    from flask_appbuilder.security.manager import AUTH_OAUTH
    AUTH_TYPE = AUTH_OAUTH
    AUTH_ROLE_PUBLIC = 'Public'
    AUTH_USER_REGISTRATION = True
    AUTH_USER_REGISTRATION_ROLE = "Viewer"  # default role
    AUTH_ROLES_MAPPING = {
        "SVC_DataCOE_Analyst": ["Admin"]
      }
    AUTH_ROLES_SYNC_AT_LOGIN = True
    PERMANENT_SESSION_LIFETIME = 1800

    OAUTH_PROVIDERS = [
        {
            'name': 'okta',
            'icon': 'fa-circle-o',
            'token_key': 'access_token',
            'remote_app': {
                'client_id': '0oaoelqqkzF52HT2J5d7',
                'client_secret': 'MS5tiT2t6tlguCc1jOOEGYtzJIGvQ697Dh615ZPjJMScSTcjkXRfvAFW5-fWgazx',
                'api_base_url': 'https://dev-70294059.okta.com',
                'access_token_url': 'https://dev-70294059.okta.com/oauth2/default/v1/token',
                'authorize_url': 'https://dev-70294059.okta.com/oauth2/default/v1/authorize',
                'client_kwargs': {
                    'scope': 'openid profile email',
                },
                'userinfo_endpoint': 'https://dev-70294059.okta.com/oauth2/default/v1/userinfo',
            }
        }
    ]

  #   import os
  #   from flask_appbuilder.security.manager import AUTH_OAUTH

  #   AUTH_TYPE = AUTH_OAUTH
  #   AUTH_USER_REGISTRATION = True
  #   AUTH_USER_REGISTRATION_ROLE = "Admin"
  #   AUTH_ROLES_SYNC_AT_LOGIN = True
  #   AUTH_BACKENDS = ['airflow.www.security.SecureOAUTHUserInfoBackend']

  #   AUTH_ROLES_MAPPING = {
  #       "Platform_viewer": ["Viewer"],
  #       "Platform": ["Admin"]
  #   }

#     OAUTH_PROVIDERS = [
#         {
#             'name': 'okta',
#             'icon': 'fa-circle-o',
#             'token_key': 'access_token',
#             'remote_app': {
#                 'client_id': '0oao3wrk7aga2Lj7b5d7',
#                 'client_secret': '5MpP2ReCfHZDMjEqK0lyGh4UzdkuaSbLaU8zbAweKCRrlpjFRlBTHrjyFVfPTZnc',
#                 'api_base_url': 'https://dev-70294059.okta.com/oauth2/default/v1/',
#                 'client_kwargs': {
#                     'scope': 'openid profile email groups'
#                 },
#                 'access_token_url': 'https://dev-70294059.okta.com/oauth2/default/v1/token',
#                 'authorize_url': 'https://dev-70294059.okta.com/oauth2/default/v1/authorize',
#                 'jwks_uri': 'https://dev-70294059.okta.com/oauth2/default/v1/keys'
# }
# }
#     ]


  # Number of webserver replicas
  replicas: 2

  service:
    # Configure the service type for the web server
    type: LoadBalancer

scheduler:
  replicas: 2  # Number of scheduler replicas

workers:
  replicas: 3  # Number of worker pods

resources:
  webserver:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  scheduler:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  workers:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
