name: Deploy Apache Airflow on AKS

on:
  push:
    branches:
      - main 
    paths:
      - .github/workflows/deploy.yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: pietrobolcato/install-azure-cli-action@v1.0.1

    - name: Log in to Azure using Service Principal
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Set the Azure subscription
      run: |
        az account set --subscription 34f8cfea-f56d-487f-aab8-4143af9a5d6e

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Set up kubectl to access AKS
      run: |
        az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --admin

    - name: Add Apache Airflow Helm repository
      run: |
        helm repo add apache-airflow https://airflow.apache.org
        helm repo update
        pip install Flask flask-appbuilder Flask-OAuthlib oauthlib


    - name: Deploy Apache Airflow using Helm
      run: |
        helm status airflow --namespace airflow
        helm history airflow --namespace airflow


        helm upgrade --install airflow apache-airflow/airflow --namespace airflow --create-namespace -f ./helm-values.yaml --force

    - name: Verify Airflow pods are running
      run: |
        kubectl get pods -n airflow

